### ISSUE TITLE
Better package name

### ISSUE THREAD

**Issue by btupper** [BigelowLab/nfsc-cpr#3]
I picked `nfsccpr` when we had only one data source.  Would `cprdata` be a more generalized name?  Best to chose before this gets used by anyone.

**Comment by SeascapeScience** [comment]
I'm okay with that. It's possible we could broaden into other cpr datasets as well. Say, from canada or other parts of the N Atlantic. Would you want those to live here as well? If so, then cprdata would be a good name.

**Comment by btupper** [comment]
Done!
